### ISSUE TITLE
Exits process when there are no storms instead of throwing an error

### ISSUE THREAD

**Issue by kbvaczi** [aaronalbright/ibis-gis#6]
I'm looking into using ibis-gis in one of my projects, but right now the package exits my node.js process anytime I try to fetch when there is no data (e.g. outside of hurricane season). I would need to be able catch an error or find some way to gracefully fail after attempting to fetch when there is no data.  Please advise.

**Comment by aaronalbright** [comment]
I apologize for the oversight. It will no longer exit the process but now throw an error.
